### ISSUE TITLE
This is (not) broken (at all)!

### ISSUE THREAD

**Issue by blaasvaer** [tudouui/tpm#2]
The tpm command is not found after installation ...

**Comment by ydream** [comment]
Use ytpm command. See details at README below.

Sent from my iPhone

在 2018年3月23日，下午5:57，Sam Blåsvær <notifications@github.com<mailto:notifications@github.com>> 写道：


The tpm command is not found after installation ...

**Comment by blaasvaer** [comment]
Then I get: 
```
File not found: tpm-config.js
```

**Comment by blaasvaer** [comment]
I'm trying to install a remote module from totaljs.com AddDesigner which states to do:

```
tpm install https://designer.totaljs.com/packages/caj11e7kod13f417s71e0gi8a1d2vx.package
```

**Comment by blaasvaer** [comment]
I'm not sure this is even the right module ... yeah, the web can be confusing ; )

**Comment by ydream** [comment]
tpm is for JS file build purpose only such as the functionality of Webpack.  not an 'Package Manager' like npm.

**Comment by blaasvaer** [comment]
OK, so I just totally confused totaljs tpm command with this module. It's part of the total.js framework – and you have to install it as a global module. Maybe some other dude runs into this issue some day and may find this info in here useful.

**Comment by blaasvaer** [comment]
Sorry for any disturbance I may have caused in your life ...
